### ISSUE TITLE
Using a Schedule that includes a '/' breaks the container.  

### ISSUE THREAD

**Issue by mitcheaton1** [wercker/cronetes#7]
I'm using kubernetes and am trying to schedule a job every 10 minutes. 
The cron looks like - schedule: */10 * * * * 
wrapping the config.yml into the docker container and running it, I get 
`did not find expected alphabetic or numeric character at line 2, column 14`

I then tried putting the schedule in quotes " */10 * * * * " 
This just spins up jobs rampantly. It seems to ignore teh schedule entirely. 
Am i missing something?

**Comment by allansene** [comment]
Yes... This is not a regular unix crontab, but a Go Cron (https://godoc.org/github.com/robfig/cron)

Actually your second try, with quotes, is spawning a job every 1/10 seconds!

**Comment by mitcheaton1** [comment]
I realized that.... my bad. Thanks for following up!

**Comment by mitcheaton1** [comment]
One last question. I'm adding the job to config.yaml to reap jobs, but the reaping doesn't seem to work. I add the the label cronetes: true in the config.yaml file for all the scheduled jobs I have at the job and pod level. Am I missing something?
