### ISSUE TITLE
Errors out, saying "the server does not allow access to the requested resource (post jobs.batch)"

### ISSUE THREAD

**Issue by cedrichan** [wercker/cronetes#9]
Hi, we're trying out cronetes in our cluster, and when it comes time to run the scheduled job, it prints this error message:

```
time="2017-06-12T23:37:00Z" level=error msg="Unable to create job" error="the server does not allow access to the requested resource (post jobs.batch)" jobName=test
```
This is using a service account with all permissions granted.
I'm guessing somewhere along the line kubernetes deprecated the `jobs.batch` resource.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cedrichan** [comment]
Eeep, it was a misconfiguration in my cluster. Sorry for the false alarm.

**Comment by ingshtrom** [comment]
@cedrichan what was the misconfiguration? I have this same problem and cannot figure it out.

**Comment by cedrichan** [comment]
The service account for the pod did not have permission to access the "jobs" resource. We created a new SA bound to a role that has the permission, then used it in the pod spec.

**Comment by ingshtrom** [comment]
awesome, thank you
